repos:
    -   repo: https://github.com/pycqa/isort
        rev: 5.10.1
        hooks:
        -    id: isort
             additional_dependencies: ["colorama>=0.4.3"]

    -   repo: https://github.com/psf/black
        rev: 22.3.0
        hooks:
        -   id: black
            args: [--skip-magic-trailing-comma]

    -   repo: https://gitlab.com/pycqa/flake8.git
        rev: 3.9.2
        hooks:
        -   id: flake8
            entry: bash -c 'exec env PYFLAKES_NODOCTEST=TRUE'

    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.942
        hooks:
        -   id: mypy
            args: [--strict, --ignore-missing-imports, --show-error-codes]
            exclude: (data|out)/