site_name: geoconverter
repo_url: https://github.com/ashnair1/geoconverter
repo_name: ashnair1/geoconverter
use_directory_urls: False
#strict: true

        
# Configuration
theme:
  name: material
  language: en
  icon:
    logo: material/earth-arrow-right
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
  - scheme: geo-light
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta

plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
          - import sys
          - sys.path.append("docs")
          selection:
            new_path_syntax: yes
          rendering:
            show_root_heading: true
            show_source: true
          
      watch:
        - geoconverter
  - gen-files:
      scripts:
       - docs/gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ashnair1/geoconverter
      name: Github
    - icon: material/email
      link: "mailto:ashnair0007@gmail.com"
