name: Build executables

on:
  push:
    tags:
      - 'v*'
    branches:
      - dem


jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.7'
    - name: Install dependencies (Linux)
      run: |
        python -m pip install --upgrade pip
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        python -m pip install GDAL numpy pyinstaller wheel
        export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
      if: ${{ runner.os == 'Linux' }}

    - name: Install conda (Windows)
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.7
        channels: conda-forge
        channel-priority: strict
      if: ${{ runner.os == 'Windows' }}
    - name: Install conda dependencies (Windows)
      run: |
        conda install gdal pyinstaller
      if: ${{ runner.os == 'Windows' }}

    - name: Install Cesium Terrian Builder
      run: |
        git clone https://github.com/ashnair1/cesium-terrain-builder.git && \
        cd cesium-terrain-builder && \
        git checkout gdal3.4
        mkdir build && cd build && cmake .. && sudo make install
        which gdalinfo
        ctb-tile --version

    - name: Build distribution (Linux)
      run: |
        pyinstaller --onefile gdal_extras/app.py --add-binary "libctb.so:lib"
      if: ${{ runner.os == 'Linux' }}
    
    - name: Build distribution (Windows)
      run: |
        pyinstaller --onefile gdal_extras/app.py --add-binary "libctb.so;lib"
      if: ${{ runner.os == 'Windows' }}

    - name: Upload artifact (Linux)
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: dist/app
      if: ${{ runner.os == 'Linux' }}

    - name: Upload artifact (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: app.exe
        path: dist\app.exe
      if: ${{ runner.os == 'Windows' }}
