name: Build executables

on:
  push:
    tags:
      - 'v*'
    branches:
      - dem


jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      name: Install Python
      with:
        python-version: '3.7'
    - name: Install dependencies (Linux)
      run: |
        python -m pip install --upgrade pip
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        python -m pip install GDAL numpy pyinstaller wheel
        export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
      if: ${{ runner.os == 'Linux' }}

    - name: Install conda (Windows)
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.7
        channels: conda-forge
        channel-priority: strict
      if: ${{ runner.os == 'Windows' }}
    - name: Install conda dependencies (Windows)
      run: |
        conda install gdal pyinstaller
      if: ${{ runner.os == 'Windows' }}
    
    - name: Clone Cesium Terrian Builder
      uses: actions/checkout@v3
      with:
        repository: ashnair1/cesium-terrain-builder
        ref: gdal3.4
        path: cesium-terrain-builder

    - name: Install CTB (Linux)
      run: |
        cd cesium-terrain-builder
        mkdir build && cd build && cmake .. && sudo make install
        ctb-tile --version
      if: ${{ runner.os == 'Linux' }}
    
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install CTB (Windows)
      run: |
        cd cesium-terrain-builder
        mkdir build
        cd build
        cmake -G "NMake Makefiles" .. 
        nmake
        set PATH = "%cd%\src;%cd%\tools;%PATH%"
      if: ${{ runner.os == 'Windows' }}
    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Build distribution (Linux)
      run: |
        pyinstaller --onefile gdal_extras/app.py --add-binary "libctb.so:lib"
      if: ${{ runner.os == 'Linux' }}
    
    - name: Build distribution (Windows)
      run: |
        pyinstaller --onefile gdal_extras/app.py --add-binary "libctb.so;lib"
      if: ${{ runner.os == 'Windows' }}

    - name: Upload artifact (Linux)
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: dist/app
      if: ${{ runner.os == 'Linux' }}

    - name: Upload artifact (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: app.exe
        path: dist\app.exe
      if: ${{ runner.os == 'Windows' }}
