name: Build executables

on:
  push:
    branches: [ pyi ]
  pull_request:
    branches: [ pyi ]


jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.7'
    - name: Install dependencies (Linux)
      run: |
        python -m pip install --upgrade pip
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        pip install GDAL numpy pyinstaller
      if: ${{ runner.os == 'Linux' }}

    - name: Install dependencies (Windows)
      run: |
        python -m pip install --upgrade pip
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        pip install GDAL numpy pyinstaller
      if: ${{ runner.os == 'Linux' }}
    - name: Install conda (Windows)
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.7
        channels: conda-forge
        channel-priority: strict
      if: ${{ runner.os == 'Windows' }}
    - name: Install conda dependencies (Windows)
      run: |
        conda install gdal pyinstaller
      if: ${{ runner.os == 'Windows' }}

    - name: Build distribution
      run: |
        pyinstaller --onefile gdal_extras/app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: dist/app
