name: docs

on:
  push:
    branches:
      - main
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install gdal-bin libgdal-dev
          python -m pip install GDAL numpy
          export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
          python -m pip install -r docs/requirements.txt
      - name: Publish docs
        run: |
          git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
          mkdocs gh-deploy
