name: Package exe with PyInstaller - Linux

on:
  push:
    branches: [ pyi ]
  pull_request:
    branches: [ pyi ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        pip install GDAL numpy pyinstaller
    - name: Build distribution
      run: |
        pyinstaller --onefile gdal_extras/app.py
        ls
        ls gdal_extras/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: gdal-extras/gdal-extras/dist/app
